### ISSUE TITLE
Cannot find module './model/MessageResponseFailurereason'

### ISSUE THREAD

**Issue by GPGitIF** [TheSMSWorks/smsw-nodejs-sdk#1]
There's a typo in the code that is causing the build to fail when I deploy to Heroku. The source references './model/MessageResponseFailurereason' in a few places but the required file is actually named 'MessageResponseFailureReason.js' – note the capital R on reason. Currently, I'm having to clone a local version, fix the typo and deploy that to get my application to start up with out crashing.

**Comment by TheSMSWorks** [comment]
Fixed
